# ===============================
# Application
# ===============================
spring.application.name=backend

# ===============================
# MySQL Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/smart_postal_db
spring.datasource.username=root
spring.datasource.password=root1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Server
# ===============================
server.port=8080
# ===============================
# JWT (a generer toi-meme, voir etape 2)
# ===============================
jwt.secret=UVve59g1j0tRW525QiJcGR41pRZI8yy7YwfERxJ/ah6vodDmj+tp46+PfChlBxJCUwEcchCevSexRS2jOeunTQ==
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG 

# ===============================
# Compte ADMIN fixe (cree automatiquement au demarrage par DataSeeder)
# ===============================
admin.identifiant=admin
admin.password=Admin@2026

# ===============================
# Envoi d'email (SMTP Gmail - exemple)
# Remplace par tes propres identifiants. Pour Gmail : active la validation
# en 2 etapes puis genere un "mot de passe d'application" (16 caracteres).
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ton.adresse@gmail.com
spring.mail.password=mpss123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

